StoreApp/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController: Controller
    {
        
        private readonly IServiceManager _manager;

        public RoleController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            return View(_manager.AuthService.Roles);
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private  IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager manager, Cart cart)
        {
            _manager = manager;
            _cart = cart;
        }

        [Authorize]
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_cart.Lines.Count == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new {orderId = order.OrderId});
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {   
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });       
            
        }
        public IActionResult Get([FromRoute(Name="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false); 
            ViewData["Title"] = model?.ProductName;
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        Admin Panel
    </div>
    @RenderBody()
</body>
</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Admin</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a class="nav-link text-white"  aria-current="page" asp-controller="Dashboard" asp-action="Index" >Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Product" asp-action="Index" >Products(@await Component.InvokeAsync("ProductSummary"))</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Category" asp-action="Index" >Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Order" asp-action="Index" >Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Role" asp-action="Index" >Role</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="User" asp-action="Index" >User</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li>
          <a target="_blank" class="nav-link  text-white" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index" >
            <i class="fa fa-solid fa-search"></i>
            Web</a>
        </li>
        <li>
          <a target="_blank" class="nav-link  text-white" aria-current="page" asp-area="" asp-controller="Account" asp-action="Logout" >
            <i class="fa fa-solid fa-right-from-bracket"></i>
            Logout</a>
        </li>

      </ul>
    </div>
  </nav>

StoreApp/Areas/Admin/Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store App - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css">
    <link rel="stylesheet" asp-append-version="true" href="~/lib/font-awesome/css/all.css">
</head>
<body>
    <header>
        
        <partial name="_Navbar"/>
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <div>
            <partial name="_Notification"/>
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer",false)
        Footer
    </footer>
    
    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    
    @await RenderSectionAsync("Scripts",required:false)
</body>
</html>